import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/skibi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:360,height:780}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8974');
const click=a=>page.locator(`[data-action="${a}"]`).first().click();
const step=()=>page.evaluate(()=>session().step);
const tests=[];
await click('start');await click('next');await click('previous');assert.equal(await step(),0);
await click('next');await click('next');
const q=await page.evaluate(()=>activeTask().q);
await page.locator(`[data-action="select"][data-index="${q.correct}"]`).click();
await click('submit-check');await click('previous');assert.equal(await step(),1);
await page.reload();assert.equal(await step(),1);await click('next');
assert.equal(await page.evaluate(()=>session().check.correct),true);
assert(await page.locator('.option.correct').isVisible());
tests.push('Header previous step retains graded answer, shuffled option order and exact previous step across reload');
await click('next');await click('observe');await click('next');
const note='Guzowatość to część kości promieniowej. Łopatka daje dwa początki bicepsa.';
await page.locator('#recall-text').fill(note);await click('previous');assert.equal(await step(),3);
assert.equal(await page.evaluate(()=>session().practice.observe),true);
await click('next');assert.equal(await page.locator('#recall-text').inputValue(),note);
await page.evaluate(()=>window.appBack());assert.equal(await step(),3);
await click('exit');assert.equal(await page.evaluate(()=>route),'home');await click('start');assert.equal(await step(),3);
tests.push('Back preserves movement observation and unfinished Polish explanation; explicit Exit resumes exact step');
await page.evaluate(()=>{session().step=1;save();render();});
await page.locator('[data-plate="biceps-attachments"] .art-button').click();
await page.evaluate(()=>window.appBack());assert.equal(await step(),1);await page.locator('dialog').waitFor({state:'detached'});
await page.evaluate(()=>window.appBack());assert.equal(await step(),0);
await page.evaluate(()=>window.appBack());assert.equal(await page.evaluate(()=>route),'home');
tests.push('System Back closes image first, then previous lesson step, then exits from step zero');
await page.evaluate(()=>{state=freshState();state.completed=['biceps'];state.reviews.biceps={due:Date.now()-DAY,streak:0,success:0,attempts:0,history:[]};start('biceps','review');});
const review=await page.evaluate(()=>activeTask().q);await page.locator(`[data-action="select"][data-index="${review.correct}"]`).click();await click('submit-review');await click('next');
await page.locator('#recall-text').fill(note);await click('previous');assert.equal(await step(),0);await click('next');assert.equal(await page.locator('#recall-text').inputValue(),note);
await click('reveal');await page.locator('[data-action="recall-grade"][data-index="0"]').click();await click('finish-review');
const before=await page.evaluate(()=>JSON.stringify(state.reviews.biceps));
await page.evaluate(()=>action('finish-review',{}));assert.equal(await page.evaluate(()=>JSON.stringify(state.reviews.biceps)),before);
await click('previous');assert.equal(await page.evaluate(()=>route),'reviews');assert.equal(await page.evaluate(()=>state.active),null);
assert.equal(await page.evaluate(()=>state.reviews.biceps.attempts),1);
tests.push('Review permits backward study; completed review cannot record twice or return to editable result');
const coverage=[];
const ids=await page.evaluate(()=>LESSONS.map(l=>l.id));
for(const id of ids)for(let index=0;index<2;index++){
 await page.evaluate(({id,index})=>{state.completed=LESSONS.map(l=>l.id);start(id,'learn');session().step=index;render();},{id,index});
 await page.waitForFunction(()=>[...document.querySelectorAll('.teaching img')].every(i=>i.complete&&i.naturalWidth>0));
 assert(await page.locator('.term-key dt').count()>0);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
 coverage.push({id,index,plates:await page.locator('[data-plate]').evaluateAll(es=>es.map(e=>e.dataset.plate)),terms:await page.locator('.term-key dt').allTextContents()});
}
tests.push('All 20 theory sections display decoded teaching plates and definitions at 360px without overflow');
assert.deepEqual(errors,[]);
await fs.writeFile('qa/navigation-v1.2.json',JSON.stringify({tests,coverage,errors},null,2));
await browser.close();console.log('PASS '+tests.length+' navigation/coverage checks across all 20 theory sections');
